title: "JennyLab sch00l"
description: "Training del laboratorio de JennyLab"
baseurl: ""  # Déjalo vacío si tu sitio está en la raíz
url: "https://www.jennylab.site" 
theme: minima
minima:
 include_nav: true
 skin: dark
markdown: kramdown
highlighter: rouge

# Paginación (opcional)
paginate: 5
paginate_path: "/_site/posts:num/"
